package com.swiftpay.enums;

public enum Country {

    AFGHANISTAN("AF", "AFN", "Afghanistan"),
    SOUTH_AFRICA("ZA", "ZAR", "Afrique du Sud"),
    ALBANIA("AL", "ALL", "Albanie"),
    ALGERIA("DZ", "DZD", "Algérie"),
    GERMANY("DE", "EUR", "Allemagne"),
    ANGUILLA("AI", "XCD", "Anguilla"),
    NETHERLANDS_ANTILLES("AN", "ANG", "Antilles Néerlandaises"),
    ANTIGUA_AND_BARBUDA("AG", "XCD", "Antigua-et-Barbuda"),
    ARMENIA("AM", "AMD", "Arménie"),
    ANGOLA("AO", "AOA", "Angola"),
    ARGENTINA("AR", "ARS", "Argentine"),
    ARUBA("AW", "AWG", "Aruba"),
    AUSTRALIA("AU", "AUD", "Australie"),
    AUSTRIA("AT", "EUR", "Autriche"),
    AZERBAIJAN("AZ", "AZN", "Azerbaïdjan"),
    BOSNIA_HERZEGOVINA("BA", "BAM", "Bosnie-Herzégovine"),
    BAHAMAS("BS", "BSD", "Bahamas"),
    BAHRAIN("BH", "BHD", "Bahreïn"),
    BANGLADESH("BD", "BDT", "Bangladesh"),
    BARBADOS("BB", "BBD", "Barbade"),
    BELGIUM("BE", "EUR", "Belgique"),
    BELIZE("BZ", "BZD", "Belize"),
    BENIN("BJ", "XOF", "Bénin"),
    BERMUDA("BM", "BMD", "Bermudes"),
    BHUTAN("BT", "BTN", "Bhoutan"),
    BELARUS("BY", "BYN", "Biélorussie"),
    BOLIVIA("BO", "BOB", "Bolivie"),
    BOTSWANA("BW", "BWP", "Botswana"),
    BRAZIL("BR", "BRL", "Brésil"),
    BRUNEI("BN", "BND", "Brunei"),
    BULGARIA("BG", "BGN", "Bulgarie"),
    BURKINA_FASO("BF", "XOF", "Burkina Faso"),
    BURUNDI("BI", "BIF", "Burundi"),
    CAMBODIA("KHR", "KHR", "Cambodge"),
    CAMEROON("CM", "XAF", "Cameroun"),
    CANADA("CA", "CAD", "Canada"),
    CAPE_VERDE("CV", "CVE", "Cap-Vert"),
    CHILI("CL", "CLP", "Chili"),
    CHINA("CN", "CNY", "Chine"),
    CYPRUS("CY", "EUR", "Chypre"),
    COLOMBIA("CO", "COP", "Colombie"),
    COMOROS("KM", "KMF", "Comores"),
    CONGO("CG", "XAF", "Congo"),
    SOUTH_KOREA("KR", "KRW", "Corée du Sud"),
    COSTA_RICA("CR", "CRC", "Costa Rica"),
    IVORY_COST("CI", "XOF", "Côte d'Ivoire"),
    CROATIA("HR", "HRK", "Croatie"),
    CUBA("CU", "CUP", "Cuba"),
    DENMARK("DK", "DKK", "Danemark"),
    DJIBOUTI("DJ", "DJF", "Djibouti"),
    DOMINICA("DM", "XCD", "Dominique"),
    EGYPT("EG", "EGP", "Egypte"),
    UNITED_ARAB_EMIRATES("AE", "AED", "Emirats Arabes Unis"),
    ERITREA("ER", "ERN", "Erythrée"),
    SPAIN("ES", "EUR", "Espagne"),
    ESTONIA("EE", "EUR", "Estonie"),
    ESWATINI("SZ", "SZL", "Eswatini"),
    UNITED_STATES("US", "USD", "Etats-Unis"),
    ETHIOPIA("ET", "ETB", "Ethiopie"),
    FIJI("FJ", "FJD", "Fidji"),
    FINLAND("FI", "EUR", "Finlande"),
    FRANCE("FR", "EUR", "France"),
    GABON("GA", "XAF", "Gabon"),
    GAMBIA("GM", "GMD", "Gambie"),
    GEORGIA("GE", "GEL", "Géorgie"),
    GHANA("GH", "GHS", "Ghana"),
    GIBRALTAR("GI", "GIP", "Gibraltar"),
    GUINEA_BISSAU("GW", "XOF", "Guinée-Bissau"),
    GREECE("GR", "EUR", "Grèce"),
    GRENADA("GD", "XCD", "Grenade"),
    GUERNSEY("GG", "GGP", "Guernesey"),
    GUINEA("GN", "GNF", "Guinée"),
    EQUATORIAL_GUINEA("GQ", "XAF", "Guinée Équatoriale"),
    GUATEMALA("GT", "GTQ", "Guatemala"),
    GUYANA("GY", "GYD", "Guyana"),
    HONG_KONG("HK", "HKD", "Hong Kong"),
    HONDURAS("HN", "HNL", "Honduras"),
    HAITI("HT", "HTG", "Haïti"),
    HUNGARY("HU", "HUF", "Hongrie"),
    CAYMAN_ISLANDS("KY", "KYD", "Iles Caïmans"),
    SOLOMON_ISLANDS("SB", "SBD", "Iles Salomon"),
    ISLE_OF_MAN("IM", "IMP", "Ile de Man"),
    FALKLAND_ISLANDS("FK", "FKP", "Iles Falkland"),
    FAROE_ISLANDS("FO", "FOK", "Iles Féroé"),
    INDONESIA("ID", "IDR", "Indonésie"),
    IRELAND("IE", "EUR", "Irlande"),
    ITALY("IT", "EUR", "Italie"),
    INDIA("IN", "INR", "Inde"),
    IRAQ("IQ", "IQD", "Irak"),
    IRAN("IR", "IRR", "Iran"),
    ISRAEL("IL", "ILS", "Israël"),
    ICELAND("IS", "ISK", "Islande"),
    JERSEY("JE", "JEP", "Jersey"),
    JAMAICA("JM", "JMD", "Jamaïque"),
    JORDAN("JO", "JOD", "Jordanie"),
    JAPAN("JP", "JPY", "Japon"),
    KENYA("KE", "KES", "Kenya"),
    KYRGYZSTAN("KGS", "KGS", "Kirghizistan"),
    KIRIBATI("KID", "KID", "Kiribati"),
    KUWAIT("KW", "KWD", "Koweït"),
    KAZAKHSTAN("KZ", "KZT", "Kazakhstan"),
    LAOS("LA", "LAK", "Laos"),
    LATVIA("LV", "EUR", "Latvia"),
    LEBANON("LB", "LBP", "Liban"),
    LIBERIA("LR", "LRD", "Libéria"),
    LIBYA("LY", "LYD", "Libye"),
    LESOTHO("LS", "LSL", "Lesotho"),
    LITHUANIA("LT", "EUR", "Lithuanie"),
    LUXEMBOURG("LU", "EUR", "Luxembourg"),
    MALTA("MT", "EUR", "Malte"),
    MOROCCO("MA", "MAD", "Maroc"),
    MADAGASCAR("MG", "MGA", "Madagascar"),
    NORTH_MACEDONIA("MK", "MKD", "Macédoine du Nord"),
    MOLDOVA("MD", "MDL", "Moldavie"),
    MONGOLIA("MN", "MNT", "Mongolie"),
    MACAU("MO", "MOP", "Macao"),
    MAURITANIA("MR", "MRU", "Mauritanie"),
    MAURITIUS("MU", "MUR", "Maurice"),
    MALDIVES("MV", "MVR", "Maldives"),
    MALAWI("MW", "MWK", "Malawi"),
    MALI("ML", "XOF", "Mali"),
    MEXICO("MX", "MXN", "Mexique"),
    MALAYSIA("MY", "MYR", "Malaisie"),
    MONTSERRAT("MS", "XCD", "Montserrat"),
    MOZAMBIQUE("MZ", "MZN", "Mozambique"),
    MYANMAR("MM", "MMK", "Myanmar"),
    NAMIBIA("NA", "NAD", "Namibie"),
    NEPAL("NP", "NPR", "Népal"),
    NIGERIA("NG", "NGN", "Nigéria"),
    NICARAGUA("NI", "NIO", "Nicaragua"),
    NORWAY("NO", "NOK", "Norvège"),
    NEW_CALEDONIA("NC", "XPF", "Nouvelle-Calédonie"),
    NEW_ZEALAND("NZ", "NZD", "Nouvelle-Zélande"),
    OMAN("OM", "OMR", "Oman"),
    UGANDA("UG", "UGX", "Ouganda"),
    UZBEKISTAN("UZ", "UZS", "Ouzbékistan"),
    PANAMA("PA", "PAB", "Panama"),
    PAPUA_NEW_GUINEA("PG", "PGK", "Papouasie-Nouvelle-Guinée"),
    PARAGUAY("PY", "PYG", "Paraguay"),
    NETHERLANDS("NL", "EUR", "Pays-Bas"),
    PERU("PE", "PEN", "Pérou"),
    PHILIPPINES("PH", "PHP", "Philippines"),
    PAKISTAN("PK", "PKR", "Pakistan"),
    POLAND("PL", "PLN", "Pologne"),
    FRENCH_POLYNESIA("PF", "XPF", "Polynésie française"),
    PORTUGAL("PT", "EUR", "Portugal"),
    QATAR("QA", "QAR", "Qatar"),
    CENTRAL_AFRICAN_REPUBLIC("CF", "XAF", "République Centrafricaine"),
    RDC("CD", "CDF", "République Démocratique du Congo"),
    DOMINICAN_REPUBLIC("DO", "DOP", "République Dominicaine"),
    CZECH_REPUBLIC("CZ", "CZK", "République Tchèque"),
    UNITED_KINGDOM("GB", "GBP", "Royaume-Uni"),
    ROMANIA("RO", "RON", "Roumanie"),
    RUSSIA("RU", "RUB", "Russie"),
    RWANDA("RW", "RWF", "Rwanda"),
    SAINT_HELENA("SH", "SHP", "Sainte-Hélène"),
    SAINT_KITTS_AND_NEVIS("KN", "XCD", "Saint-Kitts-et-Nevis"),
    SAINT_LUCIA("LC", "XCD", "Sainte-Lucie"),
    SAINT_VINCENT_AND_THE_GRENADINES("VC", "XCD", "Saint-Vincent-et-les-Grenadines"),
    SAO_TOME_AND_PRINCIPE("ST", "STN", "Sao Tomé-et-Principe"),
    SAMOA("WS", "WST", "Samoa"),
    SAUDI_ARABIA("SA", "SAR", "Arabie Saoudite"),
    SENEGAL("SN", "XOF", "Sénégal"),
    SERBIA("RS", "RSD", "Serbie"),
    SEYCHELLES("SC", "SCR", "Seychelles"),
    SINGAPORE("SG", "SGD", "Singapour"),
    SIERRA_LEONE("SL", "SLE", "Sierra Leone"),
    SLOVAKIA("SK", "EUR", "Slovaquie"),
    SLOVENIA("SI", "EUR", "Slovénie"),
    SOMALIA("SO", "SOS", "Somalie"),
    SUDAN("SD", "SDG", "Soudan"),
    SOUTH_SUDAN("SS", "SSP", "Soudan du Sud"),
    SWEDEN("SE", "SEK", "Suède"),
    SWITZERLAND("CH", "CHF", "Suisse"),
    SURINAME("SR", "SRD", "Suriname"),
    SRI_LANKA("LK", "LKR", "Sri Lanka"),
    SYRIA("SY", "SYP", "Syrie"),
    THAILAND("TH", "THB", "Thaïlande"),
    TAJIKISTAN("TJ", "TJS", "Tadjikistan"),
    CHAD("TD", "XAF", "Tchad"),
    TOGO("TG", "XOF", "Togo"),
    TONGA("TO", "TOP", "Tonga"),
    TURKMENISTAN("TM", "TMT", "Turkménistan"),
    TUNISIA("TN", "TND", "Tunisie"),
    TURKEY("TR", "TRY", "Turquie"),
    TRINIDAD_AND_TOBAGO("TT", "TTD", "Trinité-et-Tobago"),
    TUVALU("TV", "TVD", "Tuvalu"),
    TAIWAN("TW", "TWD", "Taïwan"),
    TANZANIA("TZ", "TZS", "Tanzanie"),
    UKRAINE("UA", "UAH", "Ukraine"),
    URUGUAY("UY", "UYU", "Uruguay"),
    VENEZUELA("VE", "VES", "Venezuela"),
    VIETNAM("VN", "VND", "Vietnam"),
    VANUATU("VU", "VUV", "Vanuatu"),
    WALLIS_AND_FUTUNA("WF", "XPF", "Wallis-et-Futuna"),
    YEMEN("YE", "YER", "Yémen"),
    ZAMBIA("ZM", "ZMW", "Zambie"),
    ZIMBABWE("ZW", "ZWL", "Zimbabwe");


    private final String codeISO;
    private final String currency;
    private final String name;

    Country(String codeISO, String currency, String name) {
        this.codeISO = codeISO;
        this.currency = currency;
        this.name = name;
    }

    public String getCodeISO() {
        return codeISO;
    }

    public String getCurrency() {
        return currency;
    }

    public String getName() {
        return name;
    }

    public static Country fromCode(String codeISO) {
        for (Country country: values()) {
            if (country.codeISO.equals(codeISO))
                return country;
        }

        throw new IllegalArgumentException("Country code does not exists");
    }
}

